APP_NAME=java-test

GROUP_ID=com.example
ARTIFACT_ID=java-web-app

# Use AUTO for normal CI build.
# AUTO means Jenkins will create version like 1.0.<BUILD_NUMBER>
APP_VERSION=AUTO

# Use AUTO to keep Docker tag same as APP_VERSION.
DOCKER_IMAGE_TAG=AUTO

NEXUS_URL=http://98.81.5.201:8081
NEXUS_REPO=maven-releases

AWS_REGION=us-east-1
ECR_REPO=java-test

K8S_DEPLOYMENT=java-test
K8S_SERVICE=java-test-service
APP_PUBLIC_IP=98.81.5.201

SMOKE_PATH=/health

REGRESSION_PATHS=/,/health,/hello/Siddhartha
