name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Java
        run: |
          java -version
          echo $JAVA_HOME

      - name: Build
        run: mvn clean install

      - name: Snyk Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
